package com.rainccup.aktool.core.model

import kotlinx.serialization.Serializable

@Serializable
data class Status(
    val nickName: String,
    val nickNumber: String,
    val level: Int,
    val exp: Int,
    val socialPoint: Int,
    val gachaTicket: Int,
    val tenGachaTicket: Int,
    val instantFinishTicket: Int,
    val hggShard: Int,
    val lggShard: Int,
    val recruitLicense: Int,
    val progress: Int,
    val buyApRemainTimes: Int,
    val apLimitUpFlag: Int,
    val uid: String,
    val flags: MutableMap<String, Int> = mutableMapOf(),
    val ap: Int,
    val maxAp: Int,
    val androidDiamond: Int,
    val iosDiamond: Int,
    val diamondShard: Int,
    val gold: Int,
    val practiceTicket: Int,
    val lastRefreshTs: Long,
    val lastApAddTime: Long,
    val mainStageProgress: String? = null,
    val registerTs: Long,
    val lastOnlineTs: Long,
    val serverName: String,
    val avatarId: String,
    val resume: String,
    val friendNumLimit: Int,
    val monthlySubscriptionStartTime: Int,
    val monthlySubscriptionEndTime: Int,
    val secretary: String,
    val secretarySkinId: String,
    val tipMonthlyCardExpireTs: Int,
    val avatar: Avatar? = null,
    val globalVoiceLan: String? = null,
    val classicShard: Int,
    val classicGachaTicket: Int,
    val classicTenGachaTicket: Int,
) {
    companion object {
        fun placeholder() = Status(
            nickName = "AK Tool",
            nickNumber = "1145",
            level = 120,
            exp = 0,
            socialPoint = 0,
            gachaTicket = 0,
            tenGachaTicket = 0,
            instantFinishTicket = 0,
            hggShard = 0,
            lggShard = 0,
            recruitLicense = 0,
            progress = 0,
            buyApRemainTimes = 0,
            apLimitUpFlag = 0,
            uid = "",
            ap = 0,
            maxAp = 0,
            androidDiamond = 0,
            iosDiamond = 0,
            diamondShard = 0,
            gold = 0,
            practiceTicket = 0,
            lastRefreshTs = -1,
            lastApAddTime = -1,
            registerTs = -1,
            lastOnlineTs = -1,
            serverName = "TERRA",
            avatarId = "",
            resume = "",
            friendNumLimit = 0,
            monthlySubscriptionStartTime = -1,
            monthlySubscriptionEndTime = -1,
            secretary = "",
            secretarySkinId = "",
            tipMonthlyCardExpireTs = -1,
            classicShard = 0,
            classicGachaTicket = 0,
            classicTenGachaTicket = 0,
        )
    }
}

@Serializable
data class Avatar(
    val type: String? = null,
    val id: String? = null,
)
