package com.rainccup.aktool.core.model

import kotlinx.serialization.Serializable

@Serializable
data class Status(
    var nickName: String,
    var nickNumber: String,
    var level: Int,
    var exp: Int,
    var socialPoint: Int,
    var gachaTicket: Int,
    var tenGachaTicket: Int,
    var instantFinishTicket: Int,
    var hggShard: Int,
    var lggShard: Int,
    var recruitLicense: Int,
    var progress: Int,
    var buyApRemainTimes: Int,
    var apLimitUpFlag: Int,
    val uid: String,
    var flags: MutableMap<String, Int> = mutableMapOf(),
    var ap: Int,
    var maxAp: Int,
    var androidDiamond: Int,
    var iosDiamond: Int,
    var diamondShard: Int,
    var gold: Int,
    var practiceTicket: Int,
    var lastRefreshTs: Long,
    var lastApAddTime: Long,
    var mainStageProgress: String? = null,
    var registerTs: Long,
    var lastOnlineTs: Long,
    val serverName: String,
    val avatarId: String,
    var resume: String,
    var friendNumLimit: Int,
    var monthlySubscriptionStartTime: Int,
    var monthlySubscriptionEndTime: Int,
    var secretary: String,
    var secretarySkinId: String,
    var tipMonthlyCardExpireTs: Int,
    var avatar: Avatar? = null,
    var globalVoiceLan: String? = null,
    var classicShard: Int,
    var classicGachaTicket: Int,
    var classicTenGachaTicket: Int,
) {
    companion object {
        fun placeholder() = Status(
            nickName = "AK Tool",
            nickNumber = "1145",
            level = 120,
            exp = 0,
            socialPoint = 0,
            gachaTicket = 0,
            tenGachaTicket = 0,
            instantFinishTicket = 0,
            hggShard = 0,
            lggShard = 0,
            recruitLicense = 0,
            progress = 0,
            buyApRemainTimes = 0,
            apLimitUpFlag = 0,
            uid = "",
            ap = 0,
            maxAp = 0,
            androidDiamond = 0,
            iosDiamond = 0,
            diamondShard = 0,
            gold = 0,
            practiceTicket = 0,
            lastRefreshTs = -1,
            lastApAddTime = -1,
            registerTs = -1,
            lastOnlineTs = -1,
            serverName = "TERRA",
            avatarId = "",
            resume = "",
            friendNumLimit = 0,
            monthlySubscriptionStartTime = -1,
            monthlySubscriptionEndTime = -1,
            secretary = "",
            secretarySkinId = "",
            tipMonthlyCardExpireTs = -1,
            classicShard = 0,
            classicGachaTicket = 0,
            classicTenGachaTicket = 0,
        )
    }
}

@Serializable
data class Avatar(
    var type: String? = null,
    var id: String? = null,
)
