package org.doctorate.aktool.pojo.entity

data class Status(
    var nickName: String,
    var nickNumber: String,
    var level: Int,
    var exp: Int,
    var socialPoint: Int,
    var gachaTicket: Int,
    var tenGachaTicket: Int,
    var instantFinishTicket: Int,
    var hggShard: Int,
    var lggShard: Int,
    var recruitLicense: Int,
    var progress: Int,
    var buyApRemainTimes: Int,
    var apLimitUpFlag: Int,
    val uid: String,
    var flags: MutableMap<String, Int>,
    var ap: Int,
    var maxAp: Int,
    var androidDiamond: Int,
    var iosDiamond: Int,
    var diamondShard: Int,
    var gold: Int,
    var practiceTicket: Int,
    var lastRefreshTs: Long,
    var lastApAddTime: Long,
    var mainStageProgress: String?,
    var registerTs: Long,
    var lastOnlineTs: Long,
    val serverName: String,
    val avatarId: String,
    var resume: String,
    var friendNumLimit: Int,
    var monthlySubscriptionStartTime: Int,
    var monthlySubscriptionEndTime: Int,
    var secretary: String,
    var secretarySkinId: String,
    var tipMonthlyCardExpireTs: Int,
    var avatar: Avatar?,
    var globalVoiceLan: String?,
    var classicShard: Int,
    var classicGachaTicket: Int,
    var classicTenGachaTicket: Int,
)

data class Avatar(
    var type: String?,
    var id: String?
)